name: SQLPermissions
main: io.github.mac_genius.sqlpermissions.SQLPermissions
version: 1.0
permissions:
    sqlpermissions.*:
        description: Gives access to all commands for the plugin
        children:
            sqlpermissions.perm: true

    sqlpermissions.perm:
        description: Allows a player to use the perms command
        default: op
commands:
    perm:
        description: This is the permission command.
        usage: /perm
        permission: sqlpermissions.perm
        permission-message: You do not have permission to do that.